name: CSSCONVERTER

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files
        run: ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
